name: build

on:
  push:
    branches: [main]
    paths:
      - "**.sh"
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: ./

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v8.${{ env.minor }}.${{ env.patch }}
          path: /home/runner/work/_temp/_github_home/nginx

      - name: Commit changes
        if: ${{ env.change }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update hash and version

      - name: Create GitHub release
        if: ${{ env.change }}
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/_temp/_github_home/nginx
          body: "Size: ${{ env.hash }}"
          tag_name: v8.${{ env.minor }}.${{ env.patch }}
          generate_release_notes: false
