name: test

on:
  push:
    branches-ignore: [main]
    paths:
      - "**.sh"
      - Dockerfile
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: ./

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v8.${{ env.minor }}.${{ env.patch }}
          path: /home/runner/work/_temp/_github_home/nginx
